version: "3.8"

services:
  fintrack-mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    container_name: fintrack-mariadb

  fintrack-spring:
    image: fintrack-spring
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - fintrack-mariadb
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - API_SECURITY_TOKEN_SECRET=${SECRET_KEY}
    container_name: fintrack-spring
